@startuml
	class "main.sh" as main {
		+ main()
	}
	class "input_name.sh" as input {
		+ input_names()
		+ confirm_names()
	}
	class "get_name.sh" as get {
		+ get_names()
	}
	class "log_manager.sh" as log {
		+ get_logdir()
		+ log_message()
	}

main ..> log: check and get log_dir\nsave log
get ..> input: get inputted name
input ..> log: save and show name
main ..> get: show name
@enduml
