@startuml

skinparam packageStyle rectangle
left to right direction

actor "User" as user
rectangle "load name(main.sh)" {
	usecase "execute scripts" as main
	usecase "input name" as input
	usecase "record log" as log
}

user --> main
main ..> input: << include >>
main ..> log: << write data >>
@enduml
