partition input_name.sh {
	: load input_names() from input_name.sh;
	: input any name;
	repeat
	backward: loop back to input_name;
	repeat while(confirm inputted name?) is (no: 0) not (yes: 1);
	: save log and show inputted name;
}
